
CREATE TABLE Circles (
    RADIUS NUMBER(4, 0),
    CIRCUMFERENCE NUMBER(22),
    AREA NUMBER(22),

    CONSTRAINT pk_circles PRIMARY KEY (RADIUS)
);

CREATE OR REPLACE FUNCTION PI RETURN NUMBER IS
BEGIN
    RETURN ACOS(-1);
END;
